version: "3.7"

services:
  app:
    build: ./BeProductive/
    volumes:
      - ./data/app/appsettings.json:/app/appsettings.json
      # - ./data/app/database.db:/app/database.db
    ports:
      - "500:80"
    depends_on:
      - "db"
        
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beproductive
      # PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
